### ISSUE TITLE
Changing speed modifiers

### ISSUE THREAD

**Issue by v3rtx** [openitg/itg3theme#15]
Hello,
I've tried to change speed modifiers in Metrics.ini (it works in the home theme) but I still see only default speed modifiers. 
I'm using OpenITG beta 2 for Windows.

There is modifiers sections after my changes:
#
# Modifier definitions
#
Speed=20
SpeedDefault=mod,1x
Speed,1=mod,1x;name,1x
Speed,2=mod,1.25x;name,1.25x
Speed,3=mod,1.5x;name,1.5x
Speed,4=mod,1.75x;name,1.75x
Speed,5=mod,2x;name,2x
Speed,6=mod,2.25x;name,2.25x
Speed,7=mod,2.5x;name,2.5x
Speed,8=mod,2.75x;name,2.75x
Speed,9=mod,3x;name,3x
Speed,10=mod,3.25x;name,3.25x
Speed,11=mod,3.5x;name,3.5x
Speed,12=mod,3.75x;name,3.75x
Speed,13=mod,4x;name,4x
Speed,14=mod,4.25x;name,4.25x
Speed,15=mod,4.5x;name,4.5x
Speed,16=mod,4.75x;name,4.75x
Speed,17=mod,5x;name,5x
Speed,18=mod,5.5x;name,5.5x
# For OpenITG, add M550 and remove 5.5x
Speed,19=@OPENITG and "mod,6x;name,6x" or "mod,5.5x;name,5.5x"
Speed,20=@OPENITG and "mod,c800;name,c800" or "mod,6x;name,6x"

Maybe someone can help me to determine why it doesn't change speed modifiers list?

**Comment by darklink87** [comment]
Hi Denis,

The Speed Mods are completely controlled via Lua, so you can no longer edit them in the Metrics, however with the new design there really shouldn't be a need to.

If you go in to the Options Menu, you can select Basic, Advanced, or Pro Speed Mods, and the Pro lets you pretty much create any speed that you could need during gameplay.

However if you're set on editing the Basic Speed Mods, it's controlled in one of the Lua scripts, just be careful when making changes.

Gabe Marchan

**Comment by v3rtx** [comment]
Hi Gabriel!
Thank you for quick reply, this is exactly what I was looking for!
